### ISSUE TITLE
Tests fail locally

### ISSUE THREAD

**Issue by gabebw** [gabebw/vim-spec-runner#32]
The following lines in the spec file repeatedly fail:

```
Failed examples:

rspec ./spec/plugin/spec_runner_spec.rb:9 # Vim Spec Runner :RunCurrentSpecFile is mapped to <Leader>a
rspec ./spec/plugin/spec_runner_spec.rb:107 # Vim Spec Runner :RunMostRecentSpec is mapped to <Leader>r
rspec ./spec/plugin/spec_runner_spec.rb:165 # Vim Spec Runner :RunFocusedSpec is mapped to <Leader>l
```

**Comment by gabebw** [comment]
All of the failures are related to `command_was_run`, which checks for the existence of a file:

```
  1) Vim Spec Runner :RunCurrentSpecFile is mapped to <Leader>a
     Failure/Error: expect(command_was_run).to be_true
       expected: true value
            got: false
     # ./spec/plugin/spec_runner_spec.rb:17:in `block (3 levels) in <top (required)>'

  2) Vim Spec Runner :RunMostRecentSpec is mapped to <Leader>r
     Failure/Error: expect(command_was_run).to be_true
       expected: true value
            got: false
     # ./spec/plugin/spec_runner_spec.rb:115:in `block (3 levels) in <top (required)>'

  3) Vim Spec Runner :RunFocusedSpec is mapped to <Leader>l
     Failure/Error: expect(command_was_run).to be_true
       expected: true value
            got: false
     # ./spec/plugin/spec_runner_spec.rb:172:in `block (3 levels) in <top (required)>'
```

**Comment by gabebw** [comment]
@christoomey Do you see the same failures? We check if the plug map exists, maybe we should just remove `command_was_run` checks?

**Comment by christoomey** [comment]
@gabebw I see the same failures. Not sure what the right solution is.
